// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydxuogquuguaerkndzfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkeHVvZ3F1dWd1YWVya25kemZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTMwMjAsImV4cCI6MjA3MTQyOTAyMH0.bckMDb_ptc8JOjG7imGU3crEUBzI-fQYjX5C-_0sh44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});